### ISSUE TITLE
Sugestação sobre aula 2

### ISSUE THREAD

**Issue by azmovi** [dunossauro/fastapi-do-zero#100]
Duno você acha que é valido colocar um hyperlink desse site [iana](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) quando estava comentando sobre o status code na aula 2?
![screenshot_2024-02-26_09-19-58](https://github.com/dunossauro/fastapi-do-zero/assets/67877311/0cea1616-75cb-4130-bfa4-73b4c1847d4c)
Nesse site ele especifica todos as possíveis saídas do status code, não sei se seria interessante para a curiosidade do pessoal.

**Comment by dunossauro** [comment]
Acho massa, você gostaria de enviar um PR adicionando?
