### ISSUE TITLE
Usar formatador único (ruff) ao invés de vários formatadores (blue, isort, etc.)

### ISSUE THREAD

**Issue by HenriqueAJNB** [dunossauro/fastapi-do-zero#111]
Oi @dunossauro 

Na configuração do projeto eu percebi que você usa `ruff`, `blue` e `isort`. 

Dado que o `ruff` não atua só como linter (ele também tem o formatador) não faria sentido usar somente a formatação do próprio `ruff`, configurando-a para ser compatível com `isort` ao invés de usar vários formatadores?

**Comment by dunossauro** [comment]
Fechando por inatividade
