### ISSUE TITLE
[SUGESTÃO] Colocar url do deploy

### ISSUE THREAD

**Issue by azmovi** [dunossauro/fastapi-do-zero#115]
Duno na issue #91 você pede para fazer uma tabela com o @ e repositorio da galera, seria intessante pedir para a galera colocar o link da url do site no fly io, não sei se essa ideia é boa mas estou dando

**Comment by dunossauro** [comment]
Eu diria que não faz sentido, pois se o volume de requisições for alto pra aplicação. Você pode acabar tendo de pagar a conta :(
