### ISSUE TITLE
Aula: Hashing de Senhas - passlib gera um aviso no atributo __about__ do bcrypt

### ISSUE THREAD

**Issue by sksdutra** [dunossauro/fastapi-do-zero#123]
Não creio que seja nada que fará o código deixar de funcionar, mas no arquivo "security.py", a execução da função "get_password_hash" gera o seguinte aviso (mas ainda assim retorna um resultado):

```python
get_password_hash("teste")
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/sksdutra/Dev/pyenvs/fzero-JcMmLBH0-py3.11/lib/python3.11/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
'$2b$12$MSeXkM.MoJEQj811Y8/ez.3e4V4SYWywp4dIIc/2dJDGIByq/Neh.'
```

Pelo que andei lendo, **a biblioteca passlib não é mais atualizada faz pelo menos 3 anos**: https://github.com/pyca/bcrypt/issues/684 e para continuar usando passlib, sem que esse aviso seja disparado,  é necessário forçar a bcrypt para a versão 4.0.1.

Para contornar esse aviso, usei uma sugestão na issue acima de usar diretamente o módulo bcrypt:
```python
import bcrypt

def hash_password(password: str):
    return bcrypt.hashpw(
        password=password.encode("utf-8"),
        salt=bcrypt.gensalt() # gerará um salt para cada senha, melhor tornar isso constante
    )


def verify_password(plain_password: str, hashed_password: str):
    return bcrypt.checkpw(
        password = plain_password.encode('utf-8'),
        hashed_password = hashed_password
    )
```

Resultado:
```python
>>> from security import get_password_hash, verify_password
>>> hashed_password = get_password_hash("teste")
>>> hashed_password
b'$2b$12$ns09Nm31odmHvsSfK1/EYO0cavnDgm4B4/yojJNo.qgtDT7wIsG3.'
>>> verify_password("teste", hashed_password)
True
```

Ademais, o bcrypt usa byte strings, não sei se isso afetará em alguma coisa, creio que não. Se afetar teremos que usar um decode nessas strings.

**Comment by dunossauro** [comment]
Isso está realmente tomando uma forma. O Eli foi notificado e nas próximas semanas provavelmente vamos ter um novo paco estável

https://foss.heptapod.net/python-libs/passlib/-/issues/187

**Comment by dunossauro** [comment]
Caso tenha mais alguma questão em relação a isso, só me notificar. Se não a gente fecha a issue xD

**Comment by sksdutra** [comment]
Fechado.
