### ISSUE TITLE
[MELHORIAS] Simplificação nas interações com o banco de dados via SQLAlchemy

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/fastapi-do-zero#126]
A ideia principal dessa issue é tornar as relações com o banco de dados e sqlalchemy mais palatável para iniciantes.

### Problema da herança

Exemplo da aula 04:

```python
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = 'users'

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str]
    password: Mapped[str]
    email: Mapped[str]
```

Na aula 09:

```python
class Todo(Base):
    __tablename__ = 'todos'

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str]
    description: Mapped[str]
    state: Mapped[TodoState]
    user_id: Mapped[int] = mapped_column(ForeignKey('users.id'))

    user: Mapped[User] = relationship(back_populates='todos')
```

O modelo original, definido no curso, tem alguns conceitos complexos, como o `DeclarativeBase` com uma classe vazia para ser herdada.

A relação exclusiva da classe `Base` é o uso nas migrações e nos testes.

### Nas migrações

A classe `Base` é usada para o target:

```python
rom fast_zero.models import Base

...

target_metadata = Base.metadata
```

### Nos testes

```python
@pytest.fixture()
def session():
    engine = create_engine('sqlite:///:memory:')
    Session = sessionmaker(bind=engine)
    Base.metadata.create_all(engine)
    yield Session()
    Base.metadata.drop_all(engine)
```

## O problema da fixture

As fixtures são um problema a parte em relação à complexidade. O uso do `sessionmaker` não traz nenhum valor adicional nos cenários de uso. Embora seja o padrão pra coisas mais complexas, no sentido do curso isso poderia ser substituído pelo gerenciador de contexto da própria fixture.

# Possíveis soluções

Algumas ideias básicas para melhorar a leitura e entendimento

## O caso da herança

O `DeclarativeBase` poderia ser substituída pelo `register`, tonando os modelos `dataclasses`.

```python
from sqlalchemy.orm import Mapped, mapped_column, registry


reg = registry()


@reg.mapped_as_dataclass
class User:
    __tablename__ = 'users'

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str]
    password: Mapped[str]
    email: Mapped[str]
```

Isso facilitaria o debug, pois as dataclasses tem `__repr__` por padrão e também simplifica o caso da herança. Fazendo até com que fique mais descritivo.

## O caso dos testes

Podemos usar a pópria `Session` sem o ruído deixado pelo `sessionmaker`:

```python
@pytest.fixture()
def session():
    engine = create_engine('sqlite:///:memory:')
    reg.metadata.create_all(engine)
    with Session(engine) as session:
        yield session
    reg.metadata.drop_all(engine)
```

Isso facilitaria o entendimento, pois a sessão é usada dessa forma no código-fonte, sem `sessionmaker`

**Comment by RWallan** [comment]
Talvez manter os dois exemplos como você fez com o Python 3.11 e 3.12? Na maioria das vezes ao olhar outros exemplos sempre vi com Declarative Base. Apesar de não fazer tanto sentido pra mim e o registry se tornar mais claro e simples, acredito que possa valer a pena pra não distanciar tanto do que é "comum".
