### ISSUE TITLE
Erro em task format (Windows)

### ISSUE THREAD

**Issue by vitorfehelberg** [dunossauro/fastapi-do-zero#127]
Oi, @dunossauro!

Em **Configurando o ambiente de desenvolvimento** o comando **task format** está descrito como:

`format = 'ruff check . --fix; ruff format .'`

Mas ao rodar aqui no Windows ele acusou o seguinte erro:

```
error: unexpected argument '--fix;' found

  tip: a similar argument exists: '--fix'
```

Não sei se o problema é em alguma configuração na minha máquina, mas o comando é executado ao substituir o separador por **&** ou **&&**. Não entendi muito bem o motivo e se isto seria uma solução mesmo, pois o comando **task lint** também tem este mesmo separador.

**Comment by dunossauro** [comment]
@vitorfehelberg, peguei um tempo pra tentar reproduzir no windows aqui.

Consegui:

```powershell
(fast-zero-py3.12) PS C:\Users\vagrant\fastapi-do-zero\codigo_das_aulas\12> task format
error: unexpected argument '--fix;' found
```

Fui dar uma olhada na documentação do powershell, cheguei aqui (https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipeline_chain_operators?view=powershell-7.4)

Fazendo alguns testes aqui, tudo parece bem

```powershell
PS C:\Users\vagrant\Desktop> Write-Error 'pei'; Write-Output 'Second'
Write-Error 'pei'; Write-Output 'Second' : pei
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

Second
```

Executando os comandos diretamente no shell, parece também não existir nenhum problema:

```powershell
ruff check --fix; ruff format
fast_zero\routes\todos.py:40:5: PLR0913 Too many arguments in function definition (7 > 5)
fast_zero\routes\todos.py:40:5: PLR0917 Too many positional arguments (7/5)
```

Me parece que o taskipy está com algum tipo de comportamento estranho no windows em relação a isso.

A forma talvez mais efetiva de usar talvez seja com `||`, mas não vai ter o mesmo efeito. Eu preciso sentar pra ver como fazer isso da melhor forma.
