### ISSUE TITLE
DATABASE_URL na seção de #configuracao-dos-segredos

### ISSUE THREAD

**Issue by pedroarthuralvesdeoliveira** [dunossauro/fastapi-do-zero#130]
Na aula 12, na hora de setar a database_url no fly.io está assim: 
`flyctl secrets set DATABASE_URL=postgresql://postgres:t0Vf35P21eDlIVS@fastzerodb.flycast:5432`
Mas o correto seria: 
`flyctl secrets set DATABASE_URL=postgresql+psycopg://postgres:t0Vf35P21eDlIVS@fastzerodb.flycast:5432` 
Pois senão irá dar erro de que o módulo psycopg2 não foi encontrado na hora do build.

**Comment by dunossauro** [comment]
Valeu de mais @pedroarthuralvesdeoliveira, esse é um bug que eu acabei inserindo na atualização para o python 3.12

Acabei atualizando o driver, mas equeci a aula do fly.

Vou trabalhar nisso agora. Obrigado por notificar :heart:
