### ISSUE TITLE
Instalação do pydantic[email] no macOS

### ISSUE THREAD

**Issue by matheusfs99** [dunossauro/fastapi-do-zero#137]
Na aula Estruturando o Projeto e Criando Rotas CRUD, na parte sobre estender a validação do email usando o EmailStr do pydantic, vc mostra que dá erro pq tem q instalar o email-validator.
O comando que vc indica pra instalar é `pip install pydantic[email]`, porém no macOS dá o seguinte erro: `zsh: no matches found: pydantic[email]`
Para a instalação ser efetuada com sucesso no mac, o comando de instalação deve ser `pip install 'pydantic[email]'`, com o "pydantic[email]" entre aspas.

![image](https://github.com/dunossauro/fastapi-do-zero/assets/54027873/d76bc776-f306-421a-8b55-0c8a4b5be59f)

**Comment by dunossauro** [comment]
Fala @matheusfs99 esse não é um problema da mac em si. O problema é relacionado ao zsh.

Provavelmente todos os comandos usando [] darão o mesmo problema.

O fish shell também tem esse problema.

**Comment by dunossauro** [comment]
Um ponto importante, você consegue mostrar para mim em qual aula e em qual trecho a instalação sugerida está disposta dessa forma?

Pois no curso não usamos pip e a linha colocada para essa instalação já consta com as ""

```bash
poetry add "pydantic[email]"
```

**Comment by dunossauro** [comment]
Buscando pelo trecho, acredito que tenha sido algo referente a interpretação. Pois mostro a tradução do erro e logo em seguida explico como fazer a instalação corretamente.

https://github.com/dunossauro/fastapi-do-zero/blob/d21927a5fc6096a43d3f4eddb20287084234dfc9/aulas/03.md?plain=1#L276-L296

**Comment by dunossauro** [comment]
Por agora vou fechar essa issue, se achar que algo mais precisa ser discutido, reabrimos ela
