### ISSUE TITLE
Ambiente Virtual com Poetry

### ISSUE THREAD

**Issue by afiovinicius** [dunossauro/fastapi-do-zero#138]
Após revisar a documentação com as atualizações mencionadas na live do dia 02/05/2024, percebi algo que não havia notado inicialmente. O uso do Poetry pode ser intuitivo para aqueles familiarizados com o desenvolvimento em Python, mas para os desenvolvedores novos ou com pouca experiência, pode representar um desafio. Por isso, sugiro algumas melhorias para facilitar o entendimento do controle das versões do Python com o Pyenv e, especialmente, para gerenciar o ambiente virtual com o Poetry.

Uma prática comum em muitos projetos Python que adotam o Poetry é utilizar o comando "poetry config virtualenvs.in-project true" para criar o ambiente virtual na raiz do projeto. Além disso, não identifiquei muitas complicações adicionais. Recomendo apenas uma abordagem mais didática para o uso do Poetry, destacando sua importância e simplificando o processo para os desenvolvedores menos experientes.

**Comment by dunossauro** [comment]
@afiovinicius, é exatamente por esse motivo que existe a live de python linkada nesse pedaço da instalação. Para pessoas que nunca usaram o poetry e não tem experiência com a ferramenta.

https://github.com/dunossauro/fastapi-do-zero/blob/c1b7b6549145dc0bffc02a292ffb871f92b2e0ff/aulas/01.md?plain=1#L76-L81

Sobre:

```
Uma prática comum em muitos projetos Python que adotam o Poetry é utilizar o comando "poetry config virtualenvs.in-project true"
```

Essa afirmação não totalmente verdade. Por isso acredito que não valha a pena inserir mais um bloco de complexidade na aula.

Vou fechar essa issue, mas se você acreditar que algo mais precisa ser discutido, podemos reabrir.

**Comment by afiovinicius** [comment]
Entendi, bom eu vi a aula, no caso era só uma sugestão mostrar essa parte do ambiente virtual, ativando, controlando versão do python com pyenv direto na doc, mas acho que cada pessoa tem uma forma de aprender, no meu caso prefiro escrito, grande parte deve ir pro vídeo onde você ensina sobre o poetry. (inclusive aprendi a usa ele nesse seu vídeo e uma live que vc fez)

**Comment by dunossauro** [comment]
@afiovinicius, eu entendo plenamente o que você diz. Eu também prefiro ler do que assistir. É que nesse caso específico, se toda vez que abrirmos uma tangente de uma ferramenta eu tivesse que explicar sobre ela, o escopo desse curso seria infinito.

Teria que ter um minicurso de poetry, outro de pydantic, outro de sqlalchemy, outro de passlib, e por aí vai. Como o objetivo é o fastapi, todas às vezes que um assunto vai bifurcar uma tangente eu faço o link com uma live de python que já cobrimos o assunto.
