### ISSUE TITLE
Versão mínima obrigatória de Python

### ISSUE THREAD

**Issue by adorilson** [dunossauro/fastapi-do-zero#14]
O FastAPI é construído com Python 3.7, inclusive isso é dito no primeiro parágrafo da configuração do ambiente. Entretanto, a versão 3.11 é colocada como necessária para o curso.

Portanto, qual é a versão mínima obrigatória? E qual o motivo da versão 3.11?

Essa dúvida surgiu porque uma pessoa teve problemas relacionados ao OpenSSL na instalação do pyenv. Analisando o ambiente dela, era um Ubuntu 20.04, que não tinha pacotes de python3.11, diferente do Ubuntu 22.04.

**Comment by dunossauro** [comment]
A versão mínima do curso é a 3.11 mesmo. Vamos usar recursos que só estão disponíveis nessa versão

**Comment by dunossauro** [comment]
Será que precisa ser mais explícito que isso?

https://fastapidozero.dunossauro.com/01/#ambiente-de-desenvolvimento

**Comment by adorilson** [comment]
No caso, eu me referia sobre explicitar o *porquê* precisa ser a versão 3.11.

No mínimo um "Vamos usar recursos que só estão disponíveis nessa versão", como tu disse acima. 

Mas, claro, poderia ser mais elaborado também. Assim fica claro que há um motivo real e não é só porque era a versão mais nova na época da criação do material.

Por ser uma versão muito recente, pode acabar sendo uma barreira de entrada (por mais estranho que isso possa soar) ou alguém mais incrédulo ficar de boa com a versão 3.10 porque achava que nada de novo da 3.11 seria usado.

**Comment by julioformiga** [comment]
Um sugestão seria fazer com o 3.10, quando chegar num ponto que depende do 3.11, cria uma branch específica, ou até mesmo uma repo diferente, e busca continuar fazendo as alterações que precisar. É um exercício.

Outra sugestão é trazer o erro da instalação do 3.11 no Ubuntu 20.04 pelo pyenv, porque dizer que foi só relativo ao OpenSSL não diz muita coisa, algo que pode (ou não) ser resolvido com a instalação de um pacote.

De qualquer forma, veja se isso resolve. Se não, ser mais específico quanto ao erro, que pode ser até simples de resolver.

https://medium.com/thoughful-shower/how-to-install-python-using-pyenv-on-ubuntu-20-04-5db6295b804f

**Comment by adorilson** [comment]
> Um sugestão seria fazer com o 3.10, quando chegar num ponto que depende do 3.11, cria uma branch específica, ou até mesmo uma repo diferente, e busca continuar fazendo as alterações que precisar. É um exercício.
> 

A pessoa vai fazer com a 3.8. Como é uma pessoa com experiência não será um grande problema esse fluxo, mas para pessoas mais novatas pode ser. 

> Outra sugestão é trazer o erro da instalação do 3.11 no Ubuntu 20.04 pelo pyenv, porque dizer que foi só relativo ao OpenSSL não diz muita coisa, algo que pode (ou não) ser resolvido com a instalação de um pacote.
> 

Eu acabei não trazendo porque não era essa a intenção.  De qualquer forma, foi essa a mensagem dela para mim

```
tou seguindo aquele curso lá do fastapi, mas o cara usa o pyenv. aí deu pau, não instala versão nenhuma dentro dele. já perdi muito tempo.
várias pessoas tiveram o mesmo problema:
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
cada um resolve de um jeito e outros não tem jeito que dê (meu caso)
```

Não sei o quanto isso de não ter tido jeito é o ambiente ser um WSL.

> De qualquer forma, veja se isso resolve. Se não, ser mais específico quanto ao erro, que pode ser até simples de resolver.
> 
> https://medium.com/thoughful-shower/how-to-install-python-using-pyenv-on-ubuntu-20-04-5db6295b804f

Tem outra indicação sem um muro na frente? Sei que consigo achar muita coisa com uma busca, mas queria a indicação de um humano mesmo.

**Comment by dunossauro** [comment]
> Um sugestão seria fazer com o 3.10, quando chegar num ponto que depende do 3.11, cria uma branch específica, ou até mesmo uma repo diferente, e busca continuar fazendo as alterações que precisar. É um exercício.

Não tenho nenhum intuito de alterar a versão do curso para ser menor que 3.11, dado o ponto em que já estamos a beira do lançamento da versão 3.12. Quando o curso for lançado em vídeo, a versão 3.11 já não será mais a versão "corrente", dado isso, já estamos "desatualizados". A versão 3.10 já não tem mais o suporte completo desde `2023-04-05`, ficando somente com bugfixes.

A ideia do curso é que ele mire o futuro e não o passado da linguagem. A versão 3.11 tem suporte de bugfixes até `2027-10`. Baixar a versão disso, só traria para o material mais problemas referentes ao futuro das releases do que ao passado.

Sei que vocês têm em mente o agora, mais tenho em mente a manutenção que terei que dar no futuro. Sendo assim, mantenho minha posição de manter a versão 3.11
