### ISSUE TITLE
Aula 05 - Testes para criar sessão no banco

### ISSUE THREAD

**Issue by lbmendes** [dunossauro/fastapi-do-zero#143]
Acabei de finalizar a aula 05 e os respectivos exercícios e após realizar a `task test` a parte de coverage mostra que ainda faltam testes no arquivo fast_zero/database.py

```console
---------- coverage: platform linux, python 3.12.3-final-0 -----------
Name                    Stmts   Miss  Cover
-------------------------------------------
fast_zero/__init__.py       0      0   100%
fast_zero/app.py           54      0   100%
fast_zero/database.py       7      2    71%
fast_zero/models.py        13      0   100%
fast_zero/schemas.py       14      0   100%
fast_zero/settings.py       4      0   100%
-------------------------------------------
TOTAL                      92      2    98%

```

Pelo HTML gerado mostra que o consta pendente de testes neste arquivo são as duas últimas linhas, as quais seguem abaixo:

```
    with Session(engine) as session:
        yield session
```

Essas duas linhas em específico devem ser testadas explicitamente? Ou devem ser ignoradas? Acho que pode ser interessante acrescentar uma menção a essas linhas na aula 05.

No mais a aula está excelente, estou adorando o curso. Abraço!

**Comment by dunossauro** [comment]
![Screenshot_20240514_001458_Firefox Focus.jpg](https://github.com/dunossauro/fastapi-do-zero/assets/6801122/491bb3f2-77b1-4b6e-b558-255b5cda9cdc)

@lbmendes tem uma menção a isso no próprio bloco.

Mas não se é suficiente

**Comment by lbmendes** [comment]
Ah verdade @dunossauro, vacilo meu. Obrigado pelo retorno! Li e fui fazendo a aula em 2 dias separados e acabei me passando nessa informação.

Uma sugestão que pode ajudar a deixar a info mais em evidência seria já deixar adicionado o comentário `# pragma: no cover` ao final dessas duas linhas no code block.

Fique a vontade para fechar a issue. Valeu!

**Comment by lbmendes** [comment]
Ah vi agora que o comentário é só um e ele já aplica a todo bloco, não precisa colocar em cada linha, show de bola. Sucesso:
```python
    with Session(engine) as session:  # pragma: no cover
        yield session
```

**Comment by dunossauro** [comment]
Acho que vou adicionar uma nota sobre isso na aula em que refatorarmos o projeto. Mas vou fechar por agora.

Obrigado @lbmendes
