### ISSUE TITLE
Dúvida de qual pasta olhar?

### ISSUE THREAD

**Issue by greghonox** [dunossauro/fastapi-do-zero#16]
Oi Pessoal, só uma dúvida quanto a organização. Cada aula se cria uma pasta com o numero da aula, isso mesmo ?
pergunto isso porque a aula 01 fica em um histórico de evolução por exemplo da aula 08. E assim por diante.

![image](https://github.com/dunossauro/fastapi-do-zero/assets/35502196/7b69fc6e-cd9d-4bb0-a2a4-3022bfbd3088)

**Comment by dunossauro** [comment]
Todo o código vai ser migrado para o outro repositório. Aqui só durante o desenvolvimento. Lá no repo estou fazendo com as gravações
