### ISSUE TITLE
Aula 01

### ISSUE THREAD

**Issue by cesargodoi** [dunossauro/fastapi-do-zero#169]
Link do projeto | Seu @ no git | Comentário (opcional)
-- | -- | --
[fast_zero](https://github.com/cesargodoi/fast_zero) | [@cesargodoi](https://github.com/cesargodoi) | muito obrigado pelo empenho e pelo conteúdo

**Comment by dunossauro** [comment]
@cesargodoi a issue de agrupamento dos projetos é a #91

**Comment by cesargodoi** [comment]
sorry... cou novo por aqui 😳
