### ISSUE TITLE
Iniciando o curso

### ISSUE THREAD

**Issue by Gui-mp8** [dunossauro/fastapi-do-zero#178]
| Link do projeto | Seu @ no git | Comentário (opcional) |
|-----------------|--------------|-----------------------|
| [fast_zero](https://github.com/Gui-mp8/fast_zero) | [@Gui-mp8](https://github.com/Gui-mp8) | Melhor Curso!

**Comment by dunossauro** [comment]
Adicionado a página: https://fastapidozero.dunossauro.com/projetos/repositorios/
