### ISSUE TITLE
Meu repositório! FastAPI_lab

### ISSUE THREAD

**Issue by tallesemmanuel** [dunossauro/fastapi-do-zero#183]
| Link do projeto | Seu @ no git         |  Comentário (opcional)                                 |
|-----------------|----------------------|-----------------------------------------------------------|
| [FastAPI_Lab](https://github.com/tallesemmanuel/fastapi_lab)       | @tallesemmanuel    | Por mais que saiba algo, vi que não sei de nada |

**Comment by dunossauro** [comment]
Adicionado a página: https://fastapidozero.dunossauro.com/projetos/repositorios/
