### ISSUE TITLE
> https://github.com/thiagosp/fast_zero_sync	thiagosp	Vamos pra cima!

### ISSUE THREAD

**Issue by thiagosp** [dunossauro/fastapi-do-zero#189]
> Link do projeto	Seu @ no git	Comentário (opcional)
> [fast_zero](https://github.com/thiagosp/fast_zero_sync)	[@thiagosp] Vamos pra cima!!!

_Originally posted by @thiagosp in https://github.com/dunossauro/fastapi-do-zero/issues/91#issuecomment-2198391529_

**Comment by dunossauro** [comment]
Atualizados na página todos os repositórios até aqui:

https://fastapidozero.dunossauro.com/projetos/repositorios/
