### ISSUE TITLE
FastAPI_Du_Zero

### ISSUE THREAD

**Issue by rodten23** [dunossauro/fastapi-do-zero#193]
Link do projeto | Seu @ no git | Comentário (opcional)
-- | -- | --
[FastAPI_Du_Zero](https://github.com/rodten23/FastAPI_Du_Zero) | [@rodten23](https://github.com/rodten23) | Implementação do material do curso sem alterações. Muito Obrigado, Dunossauro!

**Comment by dunossauro** [comment]
Já consta na issue #91
