### ISSUE TITLE
Inicio do Projeto

### ISSUE THREAD

**Issue by ArthurTZ** [dunossauro/fastapi-do-zero#199]
| Link do projeto  | Seu @ no git | Comentário (opcional) |
|-------------|:-------------:|:-------------:|
|[fast_zero](https://github.com/ArthurTZ/fast_zero) | [@ArthurTZ](https://github.com/ArthurTZ) | Inicio do projeto |

**Comment by dunossauro** [comment]
Atualizados na página todos os repositórios até aqui:

https://fastapidozero.dunossauro.com/projetos/repositorios/
