### ISSUE TITLE
Aula 01 - Linhas incorretas do pyproject.toml sendo mostradas

### ISSUE THREAD

**Issue by andrematte** [dunossauro/fastapi-do-zero#201]
![image](https://github.com/user-attachments/assets/bff1f09a-1777-4746-9ffe-9d6b4a38f1b7)

Olá!
Acompanhando aqui o curso percebi um errinho na aula de configuração de ambiente onde as linhas do arquivo pyproject.toml são mostradas. Creio que alguma linha nova tenha sido adicionada e acabou movendo as linhas corretas para baixo. Como isso pode prejudicar o entendimento do curso achei melhor reportar :)

**Comment by dunossauro** [comment]
Correção feita, muito obrigado :heart:
