### ISSUE TITLE
Sugestões Aula 06

### ISSUE THREAD

**Issue by JorgeMGuimaraes** [dunossauro/fastapi-do-zero#205]
Boa noite, camarada,

Parabéns pelo trabalho de qualidade. Se me permite, seguem meus dois tostões de contribuicão, e algumas dúvidas no meio. Valeu!

No código:
```
def create_access_token(data: dict):
```
o tipo deveria ser `Dict`, importando `from typing import Dict`.

---
```Note que a constante SECRET_KEY é usada para assinar o token, e o algoritmo HS256 é usado para a codificação. Em um cenário de produção, você deve manter a SECRET_KEY em um local seguro e não expô-la em seu código.```
Neste caso, já temos o arquivo .env, correto? Poderia ser usado aqui?

---

Vc pensa em usar typing notation para tipificar o retorno das funcões?

---

Na sessão https://fastapidozero.dunossauro.com/06/#modificando-o-endpoint-de-atualizacao-de-usuarios, no código do app.py, temos `if db_user is None:` inconsistente com a aula anterior `if not db_user:`

---

Na sessão https://fastapidozero.dunossauro.com/06/#protegendo-os-endpoints, no código `fast_zero/security.py` falta o import `from zoneinfo import ZoneInfo`

`"token"` tem aspas duplas :)

`payload: Dict` pode ser tipado para demonstrar que get vem do tipo

---

```session.scalar é usado para retornar a primeira coluna do primeiro resultado da consulta. Se nenhum usuário for encontrado, lançamos a exceção credentials_exception. Se um usuário for encontrado, retornamos esse usuário.```
Se session.scalar retorna um valor escalar (como o nome já diz) como usamos ela para retornar um modelo válido se o resultado é sucesso?

user = session.scalar(
        select(User).where(User.email == token_data.username)
    )

user é uma instância de um modelo válido

---

**Comment by dunossauro** [comment]
Olá @JorgeMGuimaraes, muito obrigado pelo carinho.

Bom... São muitas coisas, vamos por partes.

> No código:
> 
> ```
> def create_access_token(data: dict):
> ```
> 
> o tipo deveria ser `Dict`, importando `from typing import Dict`.

Não, o tipo genérico correto é mesmo `dict`, o `typing.dict` é para retrocompatibilidade com as versões passadas do python. Como estamos usando a versão 3.11+ no curso, a forma correta é usar `dict`

---

> `Note que a constante SECRET_KEY é usada para assinar o token, e o algoritmo HS256 é usado para a codificação. Em um cenário de produção, você deve manter a SECRET_KEY em um local seguro e não expô-la em seu código.` Neste caso, já temos o arquivo .env, correto? Poderia ser usado aqui?

Como disse no [próprio material](https://fastapidozero.dunossauro.com/06/#__codelineno-6-7), isso é provisório, será ajustado na aula 7, onde reoganizaremos o projeto.

---

> Vc pensa em usar typing notation para tipificar o retorno das funcões?

Não, a ideia é a aproveitar a melhor feature do python que é a dinamicidade. Só usei anotações onde achei necessário

---

> Na sessão https://fastapidozero.dunossauro.com/06/#modificando-o-endpoint-de-atualizacao-de-usuarios, no código do app.py, temos `if db_user is None:` inconsistente com a aula anterior `if not db_user:`
> 
> Na sessão https://fastapidozero.dunossauro.com/06/#protegendo-os-endpoints, no código `fast_zero/security.py` falta o import `from zoneinfo import ZoneInfo`
> 
> `"token"` tem aspas duplas :)

Vou corrigir essas coisas agora!

---

> `payload: Dict` pode ser tipado para demonstrar que get vem do tipo

Isso eu poderia usar um `TypedDict`, mas não tenho interesse nisso agora.

---

> `session.scalar é usado para retornar a primeira coluna do primeiro resultado da consulta. Se nenhum usuário for encontrado, lançamos a exceção credentials_exception. Se um usuário for encontrado, retornamos esse usuário.` Se session.scalar retorna um valor escalar (como o nome já diz) como usamos ela para retornar um modelo válido se o resultado é sucesso?
> 
> user = session.scalar( select(User).where(User.email == token_data.username) )
> 
> user é uma instância de um modelo válido

O escalar é o próprio objeto válido

**Comment by JorgeMGuimaraes** [comment]
Obrigado pela resposta tão rápida!

Ainda não cheguei na parte 7 :) , estou finalizando a 6. 

Sobre o dict, bom avisar, vou trocar no meu código.

Sobre o scalar, saquei. 

<devagando um pouco>
Agora, é uma nomenclatura que engana, se formos levar ao pé da letra, User estaria mais para um vetor  e id ou name para escalares. Enfim... não lembro dessa nomenclatura na álgebra relacional ou coisa do tipo, mas deve ter algum sentido.
</devagando um pouco>

`payload: dict`, no meu exercício vou manter. Estou usando o VS code e isso ajuda nas sugestões, como no caso do get().

Obrigado pelas explicações!

**Comment by dunossauro** [comment]
@JorgeMGuimaraes eu vou fechar essa issue, mas se quiser conversar mais. Pode colar lá no grupo do curso: https://t.me/fastapicomdunossauro
