### ISSUE TITLE
Fast Api

### ISSUE THREAD

**Issue by regianemr** [dunossauro/fastapi-do-zero#207]
| Link do projeto  | Seu @ no git | Comentário (opcional) |
|-------------|:-------------:|:-------------:|
|[Curso_FastApi](https://github.com/regianemr/CursoFastApi) | [regianemr](https://github.com/regianemr) |  | Aprendendo a usar o Fast Api

**Comment by dunossauro** [comment]
Repositório adicionado em https://fastapidozero.dunossauro.com/projetos/repositorios/
