### ISSUE TITLE
FastAPI do Zero! 

### ISSUE THREAD

**Issue by Hiroowtf** [dunossauro/fastapi-do-zero#211]
| Link do projeto  | Seu @ no git | Comentário (opcional) |
|-------------|:-------------:|:-------------:|
|[FastAPI do Zero](https://github.com/Hiroowtf/FastAPI-Dunossauro) | [ Hiroowtf  ](https://github.com/Hiroowtf) | Iniciando o Curso |

**Comment by dunossauro** [comment]
Atualizados na página todos os repositórios até aqui:

https://fastapidozero.dunossauro.com/projetos/repositorios/
