### ISSUE TITLE
Projeto do curso de fastapi Dunossauro

### ISSUE THREAD

**Issue by Pedro-hen** [dunossauro/fastapi-do-zero#212]
| Link do projeto  | Seu @ no git | Comentário (opcional) |
|-------------|:-------------:|:-------------:|
|[fast_zero](https://github.com/Pedro-hen/fast_zero) | [@Pedro-hen](https://github.com/Pedro-hen) | Aprendendo FastAPI |

**Comment by dunossauro** [comment]
Atualizados na página todos os repositórios até aqui:

https://fastapidozero.dunossauro.com/projetos/repositorios/
