### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rdgr1** [dunossauro/fastapi-do-zero#216]
| Link do projeto  | Seu @ no git | Comentário (opcional) |
|-------------|:-------------:|:-------------:|
|[fast_zero](https://github.com/rdgr1/fast_zero_API.git) | [@rdgr1](https://github.com/rdgr1) | Aprendendo FastAPI para Fins Educacionais :) |

**Comment by dunossauro** [comment]
Atualizados na página todos os repositórios até aqui:

https://fastapidozero.dunossauro.com/projetos/repositorios/
