### ISSUE TITLE
issue fastapi-do-zero

### ISSUE THREAD

**Issue by hsdanield** [dunossauro/fastapi-do-zero#219]
| Link do projeto  | Seu @ no git | Comentário (opcional) |
|-------------|:-------------:|:-------------:|
|[fast_zero](https://github.com/hsdanield/fast_zero) | [hsdanield](https://github.com/hsdanield) | Acompanhamento do curso fastapi-do-zero |

**Comment by dunossauro** [comment]
Adicionado: https://fastapidozero.dunossauro.com/projetos/repositorios/
