### ISSUE TITLE
Iniciando o Curso de Fast API do Zero

### ISSUE THREAD

**Issue by QuintelaCarvalho** [dunossauro/fastapi-do-zero#222]
| Link do projeto | Seu @ no git | Comentário |
| ---------------------- | ------------------ | ----------------- |
| [curso_fast_zero](https://github.com/QuintelaCarvalho/curso_fast_zero) |	[@QuintelaCarvalho](https://github.com/QuintelaCarvalho) | Aprendendo Sempre Mais com você Eduardo, Obrigado!

**Comment by dunossauro** [comment]
Repositório adicionado na página:

https://fastapidozero.dunossauro.com/projetos/repositorios/
