### ISSUE TITLE
curso fast_api

### ISSUE THREAD

**Issue by vallejoguilherme** [dunossauro/fastapi-do-zero#233]
| Link do projeto  | Seu @ no git | Comentário (opcional) |
|------------------|:------------:|:---------------------:|
| [fast_zero_sync](https://github.com/vallejoguilherme/fast_zero_sync.git) | [vallejoguilherme](https://github.com/vallejoguilherme) |

**Comment by taconi** [comment]
@vallejoguilherme adicione o seu repositório na issue #135 e fecha esta aqui por favor

**Comment by dunossauro** [comment]
Atualizado na página
