### ISSUE TITLE
Probleminha de versão do python na aula 10 

### ISSUE THREAD

**Issue by fabiocasadossites** [dunossauro/fastapi-do-zero#234]
Fiz esse gist, pois tive problema por causa da versão do Python na aula 10

https://gist.github.com/fabiocasadossites/7194d9c6b36eed1452547d7ea8f24bef

**Comment by taconi** [comment]
@fabiocasadossites Se você der uma lida no erro o problema vai estar lá

```shell
[...] Python version 3.11.9 is not supported by the project (3.12.*).
```

Seu projeto deve estar configurado para suportar apenas a versão **3.12**.
Basta mudar o FROM para a versão definida no seu [pyproject.toml](https://github.com/fabiocasadossites/python-curso-fastapi/blob/main/pyproject.toml#L9)


> Na versão do github oficial está com a versão 11 do Python e para funcionar precisa da versão 12

Se você olhar o [pyproject.toml](https://github.com/dunossauro/fastapi-do-zero/blob/main/codigo_das_aulas/10/pyproject.toml#L10) do código dessa aula verá que lá esta definido a versão **^3.11** o que faz aceitar qualquer versão **maior ou igual** que 3.11 e menor que 4.0.

![image](https://github.com/user-attachments/assets/2de59f1a-c6dd-403f-bc76-d69b9401ab6c)

Se você for olhar o [texto da aula](https://fastapidozero.dunossauro.com/10/#criando-nosso-dockerfile) verá a configuração do Dockerfile para ambas as versões.

![image](https://github.com/user-attachments/assets/14b50e4a-c141-4b4b-bcdf-e49bc6c0d4dd)

--- 

Espero ter ajudado 😃
