### ISSUE TITLE
Correção da função test_update_user_with_wrong_user

### ISSUE THREAD

**Issue by DanielSMReis** [dunossauro/fastapi-do-zero#243]
###### (perdoe qualquer erro ao abrir a issue, minha primeira issue de verdade ;D)
No texto da aula 8 a função test_update_user_with_wrong_user esta escrita da mesma forma que a função test_update_user(usando o user.id  do usuario logado), o que acabou causando um erro do teste supracitado uma vez que a resposta é HTTPStatus.OK.
### O codigo correto seria:

def test_update_user_with_wrong_user(client, user, token):
    response = client.put(
        f'/users/{user.id + 1}',
        headers={'Authorization': f'Bearer {token}'},
        json={
            'username': 'bob',
            'email': 'bob@example.com',
            'password': 'mynewpassword',
        },
    )
    assert response.status_code == HTTPStatus.FORBIDDEN
	assert response.json() == {'detail': 'Not enough permissions'}

**Comment by dunossauro** [comment]
Valeu pela notificação @DanielSMReis.

O @ricardo-emanuel01 acabou de enviar a correção. Assim que possível já faço o deploy. VOu fechar a issue :heart:
