### ISSUE TITLE
fastAPI

### ISSUE THREAD

**Issue by estelaoliveiradev** [dunossauro/fastapi-do-zero#255]
| Link do projeto  | Seu @ no git | Comentário (opcional) |
|-------------|:-------------:|:-------------:|
|[fastAPI-foods](https://github.com/estelaoliveiradev/fastAPI-foods) | [@estelaoliveiradev](https://github.com/estelaoliveiradev) | API adaptada |

**Comment by taconi** [comment]
@estelaoliveiradev poderia colocar na issue #91 em um comentário para deixar tudo agrupado?
