### ISSUE TITLE
Duvida no quizzes

### ISSUE THREAD

**Issue by arnaldojr** [dunossauro/fastapi-do-zero#258]
@dunossauro  oi tudo bem? estou utilizando o mkdocs_quiz em um site e gostaria de saber como vc fez para renderizar a questão com trecho de código. Questões simples está rodando tranquilo. muito obrigado. e parabéns pelo site.

https://github.com/dunossauro/fastapi-do-zero/blob/1c80246f56ca92ac5f1fd6b301bc41bc9a195333/aulas/quizes/aula_01.md?plain=1#L70C1-L90C4

**Comment by taconi** [comment]
Se não me engano é esse hook do quiz que faz essa função.

https://github.com/dunossauro/fastapi-do-zero/blob/1c80246f56ca92ac5f1fd6b301bc41bc9a195333/hooks/quiz_hook.py#L8-L11

**Comment by arnaldojr** [comment]
deu certo @taconi, muito obrigado.
