### ISSUE TITLE
[Aula 06] - Adicionar prefixo no router de autenticação e alterar código em relação a aula 05

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/fastapi-do-zero#32]
Como levantado por #31 e pelas conversas no telegram com @ricardo-emanuel01, alguns testes usam `/auth/token` e outros somente `/token`. O PR #31 resolve essa questão na aula 07 removendo o auth, mas depois de olhar a aula 08, o novo router também apresenta um prefixo. Para padronizar, acredito que adicionar o prefixo no router de autenticação faça mais sentido.

**Comment by ricardo-emanuel01** [comment]
Seria melhor mudar a tag desse router pra auth ao invés de token?

**Comment by dunossauro** [comment]
Acredito que sim @ricardo-emanuel01. Eu coloquei algumas das suas alterações do #31 na aula 07, mas vou deixar esse ponto em aberto pra gente corrigir :heart:

**Comment by dunossauro** [comment]
Nessa manutenção também é importante ter em vista as alterações feitas no PR #39, pois a estrutura do endpoint de put mudou!

**Comment by dunossauro** [comment]
A rota de PUT deve ser assim no código das aulas 06:


```python
# fast_zero/routers/users.py

@router.put('/{user_id}', response_model=UserPublic)
def update_user(
    user_id: int,
    user: UserSchema,
    session: Session,
    current_user: CurrentUser,
):
    if current_user.id != user_id:
        raise HTTPException(status_code=400, detail='Not enough permissions')

    current_user.username = user.username
    current_user.password = get_password_hash(user.password)
    current_user.email = user.email
    session.commit()
    session.refresh(current_user)

    return current_user
    ```

**Comment by dunossauro** [comment]
As alterações relacionadas a #39 já foram feitas!

**Comment by dunossauro** [comment]
Fechado por #41
