### ISSUE TITLE
[Aula 05] - Função get_current_user instanciada antes de ser criada (no step by step)

### ISSUE THREAD

**Issue by alison-carlos** [dunossauro/fastapi-do-zero#46]
A função get_current_user é usada no PUT porém ela só vai ser criada no final da página. Isso ficou um pouco confuso acho que precisa só corrigir a sequencia das explicações.

No começo da aula 5 (https://fastapidozero.dunossauro.com/05/)

![image](https://github.com/dunossauro/fastapi-do-zero/assets/23179410/fc7b7f07-d14a-46c7-9c82-aaebb2703d77)

Porém ela é criada no final da aula

![image](https://github.com/dunossauro/fastapi-do-zero/assets/23179410/0d4aa43a-3ad5-474e-9ef1-fb43c9656e9b)

**Comment by dunossauro** [comment]
Valeu pelo report @alison-carlos, muito obrigado.

Isso foi um vacilo de merge na #39 que acabei não vendo.

Vou trabalhar nisso agora :heart:

**Comment by dunossauro** [comment]
Alterações implementadas: https://fastapidozero.dunossauro.com/05/
