### ISSUE TITLE
Health check e serviço de migration no Docker Compose

### ISSUE THREAD

**Issue by ayharano** [dunossauro/fastapi-do-zero#48]
Olá ao pessoal do curso, principalmente o @dunossauro!

Tem um repositório de demonstração que eu estava baseando em partes do curso FastAPI do zero, mas como quando estava preparando a parte do Docker estava como um PR em andamento, procurei outras fontes.

Como exemplo base, tinha seguido [a receita de bolo compartilhada nesse pequeno artigo do Simon Wilison para Django](https://til.simonwillison.net/docker/docker-compose-for-django-development).

Ao contrário da parte atual do curso que é gerido por um entrypoint, naquela receita usa um serviço a parte que repliquei. Entretanto, ao rodar o serviço dava problemas do serviço de PostgreSQL não estar disponível ainda.

Considerando o que falei até agora, busquei sobre como colocar o requisito de disponibilidade dos serviços antes da aplicação FastAPI subir e fiz algumas mudanças:

1. Um [docker-compose.yml](https://github.com/ayharano/cawa/blob/d044d5796ceaec411b32fe447ec620fcf911a77a/docker-compose.yml#L18-L44) que estabelece esses requisitos para então a aplicação subir
2. Um [Dockerfile.dev](https://github.com/ayharano/cawa/blob/d044d5796ceaec411b32fe447ec620fcf911a77a/Dockerfile.dev#L1-L45) que usa [multi-stage build](https://docs.docker.com/build/building/multi-stage/) para gerar uma versão base e então configurar uma imagem para migração e outro para a aplicação em si

Considerando o intuito do curso ser uma introdução funcional do apanhado geral, não sei se seria bom abordar esses tópicos na aula de docker/docker compose, mas como em outras aplicações já passei por problemas de serviços bases não estarem de pé antes da aplicação, e dado o uso do curso para a base do repositório mencionado, achei de bom tom contribuir de volta inicialmente como uma issue e, se for o caso, posteriormente como uma PR

**Comment by dunossauro** [comment]
@ayharano, eu vou fechar essa issue, mas vou adicionar uma nota no texto quando passar pela aula de docker na revisão
