### ISSUE TITLE
Volume não definido no serviço do docker

### ISSUE THREAD

**Issue by brunosp1024** [dunossauro/fastapi-do-zero#65]
Não foi definido um volume no serviço de backend, aí as mudanças feitas localmente não refletem no container, sendo preciso reiniciá-lo toda vez. Mas quando defino um volume (.:/app) no serviço, gera um erro informando que o uvicorn (alembic, etc) não tá instalado.

**Comment by dunossauro** [comment]
Olá @brunosp1024, estamos usando o docker somente para produção. Onde pegamos todas as mudanças e layers prontos para produção. A ideia desse material não é criar um ambiente de desenvolvimento no docker, para isso configuramos todo o ambiente localmente durante o curso!
