### ISSUE TITLE
Aula 11- Deploy no fly precisa "[...] das suas informações de pagamento para continuar!"

### ISSUE THREAD

**Issue by taconi** [dunossauro/fastapi-do-zero#73]
Seguindo os passos da aula 11, um erro impede a continuação da reprodução dos passos descritos.

O comando `flyctl launch --no-deploy` após configurar a aplicação pelo navegador e clicar em `Confirm Settings!` o erro abaixo é apresentado:
![image](https://github.com/dunossauro/fastapi-do-zero/assets/44283700/495c9363-1359-4017-8165-874bb6eb7fb5)

A versão do flyctl usado é:
  `flyctl v0.1.135 linux/amd64 Commit: 4cd282a8ce995bec8fb408d880f159159eb209bc BuildDate: 2023-12-22T00:44:24Z`
Foi usado o [fastapi-ci-example](https://github.com/dunossauro/fastapi-ci-example) para fazer este teste.

Como não está descrito na aula em questão que um método de pagamento é requerido, estou considerando isso um erro, mas acredito que não cabe a mim dizer se colocar no texto essa informação será suficiente ou se a troca para uma plataforma que prove esse serviço sem essa exigência (existe?). Como a aula já está pronta acredito que o mais simples e rápido seria o primeiro.

**Comment by dunossauro** [comment]
O pior é que eu tinha adicionado isso e acabei removendo na manutenção.

https://github.com/dunossauro/fastapi-do-zero/commit/df5cfdd3b91b6bb5b3368833c5c0868b037a8c7e

Acho que vou encaixar esse texto novamente!
