### ISSUE TITLE
[Aula 01] Código do teste implementado falhando na task lint (pre_test)

### ISSUE THREAD

**Issue by lbmendes** [dunossauro/fastapi-do-zero#76]
Na aula 01 ficou faltando incluir uma linha em branco a mais nos trechos de código onde consta a função `test_root_deve_retornar_200_e_ola_mundo()` para respeitar a PEP8 (https://peps.python.org/pep-0008/#blank-lines) que pede nesses casos 2 linhas em branco.

Com isso ao rodar o teste, ao invés do esperado sucesso está ocorrendo falha na etapa de lint (pre_test):

```console
(fast-zero-py3.12) lucas@pc:~/projetos/fast_zero$ task test
--- tests/test_app.py	2023-12-31 01:45:36.254314 +0000
+++ tests/test_app.py	2023-12-31 01:45:43.675734 +0000
@@ -1,7 +1,8 @@
 from fastapi.testclient import TestClient
 from fast_zero.app import app
+
 
 def test_root_deve_retornar_200_e_ola_mundo():
     client = TestClient(app)
 
     response = client.get('/')
would reformat tests/test_app.py

Oh no! 💥 💔 💥
1 file would be reformatted, 3 files would be left unchanged.
(fast-zero-py3.12) lucas@pc:~/projetos/fast_zero$
```

**Comment by dunossauro** [comment]
@lbmendes, muito obrigado pela contribuição.

A correção já está no deploy https://fastapidozero.dunossauro.com/01/

Adicionei seu nome a lista de contribuições, espero que não se importe :heart:
