### ISSUE TITLE
1º parágrafo

### ISSUE THREAD

**Issue by me15degrees** [dunossauro/fastapi-do-zero#78]
Legibilidade nível 8:

"Olá, boas vindas ao curso de FastAPI!

A nossa intenção neste curso é facilitar o aprender a desenvolver APIs usando o FastAPI. Vamos explorar como integrar bancos de dados, criar testes e um sistema básico de autenticação. Tudo isso para oferecer uma boa base para quem quer trabalhar com essa tecnologia. A nossa forma de apresentar o curso é prática e cheia de informações. Ela busca trazer o que precisa para criar os nossos próprios projetos."

**Comment by dunossauro** [comment]
@me15degrees, obrigado pela ajuda :heart: já está no deploy. Adicioneu seu nome a lista de contribuições :heart:
