### ISSUE TITLE
[Aula 03] Nome do pacote para instalação do sqlite no Ubuntu/Debian

### ISSUE THREAD

**Issue by lucasmpavelski** [dunossauro/fastapi-do-zero#81]
Na nota "Caso não tenha o SQLite instalado na sua máquina:" o comando para instalar o sqlite é `sudo apt install sqlite`

Acredito que o nome do pacote do sqlite no Ubuntu e Debian seja `sqlite3`:

https://packages.debian.org/search?searchon=sourcenames&keywords=sqlite3

Testado no Debian GNU/Linux 12 (bookworm).

**Comment by dunossauro** [comment]
Já está no deploy: https://fastapidozero.dunossauro.com/

Te adicionei a lista de contribuições. Muito obrigado <3
