### ISSUE TITLE
[Aula 09] Erro no código de exemplo do conftest.py com a sessão do Postgres

### ISSUE THREAD

**Issue by brunodavi** [dunossauro/fastapi-do-zero#84]
Tópico onde o erro foi encontrado: [Executando os testes no PostgreSQL](https://fastapidozero.dunossauro.com/09/#executando-os-testes-no-postgresql)

Local dos erros:
![09_errors](https://github.com/dunossauro/fastapi-do-zero/assets/48166556/2886cad3-218c-45fd-97c2-ab98e7592bf4)

O meu código funcionou apenas quando deixei assim:
```python
import factory
import pytest
from fastapi.testclient import TestClient
from sqlalchemy import StaticPool, create_engine
from sqlalchemy.orm import sessionmaker

from fast_todo.app import app
from fast_todo.database import get_session
from fast_todo.models import Base, User
from fast_todo.settings import Settings
from fast_todo.security import get_password_hash

# Resto do código...

@pytest.fixture
def session():
    engine = create_engine(
        Settings().DATABASE_URL,
        poolclass=StaticPool,
    )

    Session = sessionmaker(bind=engine)
    Base.metadata.create_all(engine)

    yield Session()

    Base.metadata.drop_all(engine)

# Resto do código...
```

Pois quando executava sem o `StaticPool` depois que ele passava do teste de `auth.py` o do `app.py` ficava parado sem executar, então supus que poderia ser por causa de não ter as configurações de execução que você explicou no começo da aula que são executadas de forma paralela

**Comment by dunossauro** [comment]
@brunodavi, obrigado pelo report, meu querido :heart: 

Acabei de corrigir a parte do texto. Em relação ao código fonte, acabei de testar aqui e está funcional. Não é recomendado usar o `StaticPool ` quando usamos postgres. Algo deve ter acontecido no desenvolvimento da sua aplicação em específico. Provavelmente algum erro direcionado pelo pŕoprio curso. Seu repositório está aberto?

Para efeito de comparação, o código usado para efetuar o comando `docker-compose run --entrypoint="bash" fastzero_app` está aqui: https://github.com/dunossauro/fastapi-do-zero/tree/main/codigo_das_aulas/09

Vou fechar a issue por hora, qualquer coisa podemos reabrir!

**Comment by dunossauro** [comment]
A correção já está no deploy: https://fastapidozero.dunossauro.com/

**Comment by brunodavi** [comment]
Obrigado, vou verificar
