### ISSUE TITLE
Farante

### ISSUE THREAD

**Issue by daltroizaias** [dunossauro/fastapi-do-zero#85]
Acredito que seja farão a palavra correta 

Item 3 da integração continua 

"Instalar as dependências do projeto: farante que todas as bibliotecas necessárias estão disponíveis para a execução dos testes."

**Comment by daltroizaias** [comment]
Outro erro de gramatica 
"
host and accepting TCP/IP connections? traduzida de forma literal quer dizer "O servidor rodando está aceitando conexões TCP/IP?". Isso quer dizer que ouve uma tentativa de comunicação com localhost:5432, porém, não ouve resposta. Para corrigir esse comportamento teremos que partir para a configuração do postgres no workflow."

Ouve = houve

**Comment by dunossauro** [comment]
Muito obrigado @daltroizaias :heart: 

A correção já está no deploy: https://fastapidozero.dunossauro.com/
