### ISSUE TITLE
Apêndices

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/fastapi-do-zero#87]
A ideia dessa issue é reunir insumos para possíveis apêndices no material. No sentido de termos mais aulas, não vinculadas originalmente ao conteúdo, mas que se apoiem no fato dos conceitos básicos já terem sido explorados no material geral.

Por exemplo:

1. Interagindo com templates [Jinja](https://jinja.palletsprojects.com/)
2. Banco de dados de documentos com [Beanie](https://beanie-odm.dev/)
3. Deploy em uma VPS
4. Gunicorn + Uvicorn
5. Tarefas em Backgroud
6. Gerenciamento de usuários com [FastAPI-Users](https://fastapi-users.github.io/fastapi-users/)
7. Exercícios resolvidos
8. ...

Temas que podem se somar aos fundamentos já explicados e expandir os horizontes com FastAPI.

A prioridade dessa issue é **extremamente baixa**, são só ideias na minha cabeça. Quem sabe esse material não pode até ser desenvolvido de forma colaborativa. São só ideias!

Quem quiser e puder, pode se sentir confortável para conversarmos nessa issue.

**Comment by azmovi** [comment]
Duno estou criando o repositorio para os Exercícios resolvidos, não sei ja tem alguem fazendo mas de qualquer foma estou deixando o link aqui, [repositorio](https://github.com/azmovi/exercicios-resolvidos-fastapi-do-zero)

**Comment by dunossauro** [comment]
Fechando essa issue para um momento mais oportuno
