### ISSUE TITLE
Vídeo Aulas

### ISSUE THREAD

**Issue by afiovinicius** [dunossauro/fastapi-do-zero#88]
Cai de paraquedas nesse repositório e vi agora o site, queria saber se tem em formato de vídeo também ou apenas a "doc" do curso... Para mim é fácil e até gosto mais assim, com uma bela "documentação" do curso, onde posso recorrer a qualquer momento, mas para amigos e alguns devs que Jr que treino no meu time vídeos são mais fáceis.

**Comment by dunossauro** [comment]
Fala @afiovinicius, os vídeos ainda não saíram. Mas na documentação tem uma explicação sobre isso. Vão sair em breve :heart: 

Assim que eu terminar de escrever.


https://fastapidozero.dunossauro.com/#onde-o-curso-sera-disponibilizado
