### ISSUE TITLE
Fixtures do Pytest e Freezegun

### ISSUE THREAD

**Issue by davidpalves** [dunossauro/fastapi-do-zero#9]
## Problema
No tópico [[REV] Tornando o sistema de autenticação robusto](https://fastapidozero.dunossauro.com/07/), na [seção de testes de expiração de token](https://fastapidozero.dunossauro.com/07/#testando-a-expiracao-do-token), temos o seguinte código apresentado:

```python
from freezegun import freeze_time

@freeze_time('2023-07-14 12:00:00')
def test_token_expiry(client, user, token):
    with freeze_time('2023-07-14 12:31:00'):
        response = client.delete(
            f'/users/{user.id}',
            headers={'Authorization': f'Bearer {token}'},
        )

    assert response.status_code == 401
    assert response.json() == {'detail': 'Could not validate credentials'}
```

No entanto, localmente, e pelas minhas pesquisas em outros lugares também, creio que a utilização do decorator `freeze_time` nesse caso afeta o teste, mas não afeta a fixture de geração de Token. O que faz com que o teste falhe.

## Propostas de solução

1. Uma das soluções encontradas foi usar algo como o [pytest-freezegun](https://github.com/ktosiek/pytest-freezegun), que usa markers do _pytest_ pra conseguir fazer com que a fixture seja afetada, então teríamos algo do tipo:
```python
from freezegun import freeze_time
from pytest_freezegun import pytest

@pytest.mark.freeze_time('2023-07-14 12:00:00')
def test_token_expiry(client, user, token):
    with freeze_time('2023-07-14 12:31:00'):
        response = client.delete(
            f'/users/{user.id}',
            headers={'Authorization': f'Bearer {token}'},
        )

    assert response.status_code == 401
    assert response.json() == {'detail': 'Could not validate credentials'}
```

2. Outra solução encontrada foi a utilização do decorator `freeze_time` diretamente em uma fixture, dessa forma, sempre que essa fixture em questão for utilizada, ela vai estar num momento "congelado" (eu, particulamente, não sou muito fã dessa abordagem), algo assim:
```python
@pytest.fixture
@freeze_time('2023-07-14 12:00:00')
def expired_token(client, user):
    response = client.post(
        '/token',
        data={'username': user.email, 'password': user.clean_password},
    )
    return response.json()['access_token']

```
---------

Não sei se foi algum passo que acabei pulando ou se alguém mais passou por isso, mas esse foi um ponto que acabei encontrando. Seria massa se a gente pudesse, talvez, apontar isso durante o curso pra que ninguém fique travado sem entender porque esse teste não tá funcionando. O que acha? 😬

**Comment by dunossauro** [comment]
Opa querido, valeu pela menção.

Como essa aula ainda está em REV, eu não atualizei todas as coisas ainda. Mas o [código-fonte dessa aula](https://github.com/dunossauro/fastapi-do-zero/blob/main/codigo_das_aulas/07/tests/test_auth.py#L47-L62) já está diferente. Preciso alterar o texto:

```python
def test_token_expiry(client, user):
    with freeze_time('2023-07-14 12:00:00'):
        response = client.post(
            '/token',
            data={'username': user.email, 'password': user.clean_password},
        )
        assert response.status_code == 200
        token = response.json()['access_token']

    with freeze_time('2023-07-14 13:00:00'):
        response = client.post(
            '/refresh_token',
            headers={'Authorization': f'Bearer {token}'},
        )
        assert response.status_code == 401
        assert response.json() == {'detail': 'Could not validate credentials'}
```

Eu vou deixar essa issue aberta até alterar o texto. Mas já fica aqui como será a correção
