### ISSUE TITLE
[Aula 06] Verificar exemplo no tópico 'Aplicação da proteção ao endpoint'

### ISSUE THREAD

**Issue by mmaachado** [dunossauro/fastapi-do-zero#94]
Durante a aula 06 no tópico **Aplicação da proteção ao endpoint**, o código de exemplo atribui ao campo _current_user.password_ o valor _user.password_, mas anteriormente fizemos a alteração para  _get_password_hash(user.password)_

**Comment by dunossauro** [comment]
Valeu meu querido, muito obrigado :heart: 

O pior é que isso já tinha sido resolvido em #30, devo ter feito alguma cagada aqui. hahahahaha

Valeu DE MAIS!!!
