### ISSUE TITLE
No macos o comando pyenv update não existe

### ISSUE THREAD

**Issue by alphabraga** [dunossauro/fastapi-do-zero#97]
Olá,

No macOS o comando `pyrnv update` não existe.

Mais detalhes sobre meu ambiente

➜  ~ sw_vers # mostra a versao do macos
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
➜  ~ pyenv --version
pyenv 2.3.35

https://github.com/dunossauro/fastapi-do-zero/blob/318c23d84e829dd0118215010d89a74776592564/aulas/01.md?plain=1#L62

**Comment by dunossauro** [comment]
Como você instalou o pyenv? Pelo pyenv-installer? Ou pelo pyenv puro? Pelo brew?

**Comment by dunossauro** [comment]
@alphabraga vou fechar essa issue por inatividade. Caso queira me atualizar depois, pode reabrir a issue
